### ISSUE TITLE
the software closed because an error occurred

### ISSUE THREAD

**Issue by Nagol12344** [Shock95x/AuctionHouse#40] opened 2020-06-30 21:34 UTC
### Issue description
when I try to buy something I immediately get kicked out in console it said I left because of timeout no other messages show

### Steps to reproduce the issue
1. open Minecraft on your Nintendo switch
2. open a featured server to get to the server list
3. go on to your server
4. type in the command /ah
5.buy an item
6. get greeted with the message the software closed because an error occurred
7 DONE

### OS and versions
* PocketMine-MP:3.14
* Plugin version: latest version
* Server OS: I don't know I'm using a server hosting website

### Error/Crash log (If available)

```
[17:34:29] [Server thread/INFO]: [StaffChat] <Staff> GameDiamond3757 disconnected
[17:34:29] [Server thread/INFO]: GameDiamond3757[/38.142.223.194:33744] logged out due to timeout
```

**Comment by Shock95x** [comment] 2020-06-30 23:05
Duplicate of issue #38

**Closed by Shock95x** 2020-06-30 23:05 UTC
Labels: duplicate
