### ISSUE TITLE
when withdrawing from auction error.

### ISSUE THREAD

**Issue by Wayder228** [Shock95x/AuctionHouse#110] opened 2022-04-28 16:50 UTC
### Issue description
Write the issue description here

### Steps to reproduce the issue
1. When withdrawing from aha error.
2. ...

### OS and versions
* PocketMine-MP: 4.2.0
* Plugin version: Release and development
* Server OS:

### Error/Crash log (If available)

```
Error: Only arrays and Traversables can be unpacked
File: plugins/AuctionHouse.phar/src/shock95x/auctionhouse/menu/ExpiredMenu
Line: 55
Type: Error

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: AuctionHouse

Code:
[46] 	}
[47] 
[48] 	public function renderListings(): void {
[49]         foreach($this->getListings() as $index => $listing) {
[50] 			$item = clone $listing->getItem();
[51] 
[52] 			$expiredItem = Locale::get($this->player, "expired-item");
[53] 
[54] 			$lore = str_ireplace(["{PRICE}"], [$listing->getPrice(true, Settings::formatPrice())], preg_filter('/^/', TextFormat::RESET, $expiredItem));
[55] 			$lore = Settings::allowLore() ? [...$item->getLore(), ...$lore] : $lore;
[56] 			$item->setLore($lore);
[57] 
[58]             $this->getInventory()->setItem($index, $item);
[59]         }
[60]        	parent::renderListings();
[61] 	}
[62] 
[63] 	public function handle(Player $player, Item $itemClicked, Inventory $inventory, int $slot): bool {
[64] 		Await::f2c(function () use ($player, $slot, $itemClicked, $inventory) {
[65] 			$storage = DataStorage::getInstance();
```

**Comment by Shock95x** [comment] 2022-05-05 04:37
Duplicate of #109

**Closed by Shock95x** 2022-05-05 04:37 UTC
Labels: bug, duplicate

**Comment by Wayder228** [comment] 2022-05-06 20:09
> Дубликат [# 109](https://github.com/Shock95x/AuctionHouse/issues/109)

I'm sorry, but it just took a long time to answer.

**Comment by SiahRBLX** [comment] 2022-05-11 17:12
When buying from AH or removing i get a black screen
