### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ZenZenXDz** [Shock95x/AuctionHouse#36] opened 2020-06-15 00:29 UTC
When I buy something at the AH the whole server crash.

**Comment by Shock95x** [comment] 2020-06-15 00:36
Provide the crash dump here

**Comment by Shock95x** [comment] 2020-06-15 00:52
@ZenZenXDz I wasn't able to reproduce this, are you using v1.1.0?

**Comment by Nagol12344** [comment] 2020-07-01 21:00
it's confirmed

**Comment by Shock95x** [comment] 2020-07-01 21:04
@Nagol12344 This isn't related to #38 if that's what you're talking about

**Comment by Nagol12344** [comment] 2020-07-02 17:17
it is

**Comment by Shock95x** [comment] 2020-07-02 17:29
Nope, if it was then only the client would crash. He said that the whole server crashed.

**Comment by Shock95x** [comment] 2020-08-27 19:08
Closing due to no additional information

**Closed by Shock95x** 2020-08-27 19:08 UTC
Labels: unconfirmed
